apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: user
          image: hxshxn/auth-service:latest
          ports:
            - containerPort: 5002
          env: 
            - name: MONGO_URI
              value: "mongodb+srv://wajeenpc:Aa1234aA@cluster0.j6vablp.mongodb.net/test"