apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
stringData:
  JWT_PRIVATE_KEY: "qiwuegquwe123123bahsbd213123asdhuaisdguashd"  #"your_jwt_private_key_here"
  AUTH_EMAIL: "shayeedwajee@gmail.com" #"your_email@example.com"
  AUTH_PASS: "mnsjrbqxpkjznfli" #"your_email_password"
  MONGO_URI: "mongodb+srv://username:password@cluster0.j6vablp.mongodb.net/test"