apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: hxshxn/frontend-service:latest 
        imagePullPolicy: Always
        
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_BASE_URL
          value: "http://api-gateway:8000"
        - name: VITE_GOOGLE_MAPS_API_KEY
          valueFrom: 
            secretKeyRef:
              name: frontend-secrets  
              key: google-maps-api-key
