apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery
          image: hxshxn/delivery-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5006
          env: 
            - name: MONGO_URI
              value: "mongodb+srv://HeshanTest:ggsl1974@mern.4zq74gy.mongodb.net/foodorders"