apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user
          image: hxshxn/user-service:latest
          ports:
            - containerPort: 5001
          env: 
            - name: MONGO_URI
              value: "mongodb+srv://HeshanTest:ggsl1974@mern.4zq74gy.mongodb.net/foodorders"